### ISSUE TITLE
Rebase off of Lazarus 3.2?

### ISSUE THREAD

**Issue by thekyriarchy** [lazarus-recovery/original_ff#3]
https://web.archive.org/web/20150218051442/http://getlazarus.com:80/download

**Comment by sierracircle** [comment]
Very helpful!! Thank you for posting that link.

**Comment by maphew** [comment]
_I dithered over creating a new "Lazarus Archeology" issue or wiki page but decided in the end it might as well be here. Normally I'd have posted something like this to a mailing list instead of an 
issue, but we don't have one of those so..._

Following the Wayback 3.2 link and some related searches led to some interesting places. Namely:

A [long thread][3] on the Chrome extension, which brought in one Karl Dearden (werehamster) who is _"one of the original developers of Lazarus ... Lazarus was owned by the business I worked for. When I left I gave full ownership of Lazarus to the other partner and agreed that I would to not make a competing product"_ and _"Whilst I cannot build a replacement for it, I can certainly help you out with info about how we solved various problems."_. The [full post][4] offers important things to consider.

> 1 - decide very early on if you're going to save just individual textareas (easy) or whole forms (significantly more difficult).
> 
> 2 - are you going to encrypt the data? If yes, that makes it a lot better privacy-wise, but it also makes the database a lot harder to search.
> 
> 3 - if you choose not to encrypt the data, then you'll have to make sure you don't save sensitive information like credit card details and passwords and such.
> 
> Some things to note:
> 
> 1  - the addon will get used by jealous people to spy on their significant others. We deliberately added the Lazarus icon to every field that was being saved so that it was significantly more difficult to use Lazarus for that purpose, but still many people asked for the feature.
> 
> 2 - we used an SQLite database with unlimited space to store the data. You should have no trouble using either that or IndexDB instead.
> 
> 3 - people will want all of their data saved forever. They'll want to be able to search it and export it to other programs (again, also for spying on people, or for use in court). And they'll get angry if you can't or won't do that for them.


That same thread features the birth of [Text Input Recovery Extension (for Chrome) ][0] by Chuck Baker. The code is [here on Github][1] but while an experienced programmer and extension developer he's been mostly solo, so GH use is shallow so far.

[3]: https://groups.google.com/a/chromium.org/forum/#!topic/chromium-extensions/aoAIue0W47o
[4]: https://groups.google.com/a/chromium.org/d/msg/chromium-extensions/aoAIue0W47o/j3Bd86piPwAJ
[0]: http://softwarebychuck.com/TIRE/TIREhomepage.html
[1]: https://github.com/Shadoefax/TIRE-for-Chrome

-----

**Comment by thekyriarchy** [comment]
Great research! Is the 3.2 code available in there somewhere? Maybe buried in archive.org somewhere?

**Comment by sierracircle** [comment]
Yes, that is great research. It would be wonderful to unearth the 3.2 extensions, which look like they were actually developed at one point. I have not been able to find them...

**Comment by maphew** [comment]
I fetched the v3.2 extension distribution archives from Wayback Machine, unpacked them with 7zip, reorganized to follow the FF directory layout, and then pushed each as separate branches to this "original_ff" repository. This may not have been the most correct thing to do, but at least everything is here in one place for someone more knowledgeable to work from.

* https://github.com/lazarus-recovery/original_ff/tree/firefox_v3.2
* https://github.com/lazarus-recovery/original_ff/tree/chrome_v3.2
* https://github.com/lazarus-recovery/original_ff/tree/safari_v3.2

**Comment by sierracircle** [comment]
@maphew   Have you by any chance tried these extensions? I am curious if they work for you. I just tried the FF 3.2, but it was not working in the most recent version of FF.

**Comment by thekyriarchy** [comment]
I had 3.2 installed for a very long time, but it stopped working with ff54  or ff55 i think.

**Comment by Tormen** [comment]
@thekyriarchy : Maybe that is the reason:

> Starting from Firefox 57, only extensions developed using WebExtensions APIs will be supported on Desktop Firefox and Firefox for Android.
> 
> Even before Firefox 57, changes coming up in the Firefox platform will break many legacy extensions. These changes include multiprocess Firefox (e10s), sandboxing, and multiple content processes. Legacy extensions that are affected by these changes should migrate to use WebExtensions APIs if they can. See the "Compatibility Milestones" document for more information.

SOURCE: https://developer.mozilla.org/en-US/Add-ons/SDK

**Comment by maphew** [comment]
closing as no longer applicable, we've moved on and have something that works!

**Comment by thekyriarchy** [comment]
oh cool, what have you moved on to?
